### ISSUE TITLE
if text get out of The image size continue writing from other side of image

### ISSUE THREAD

**Issue by Monirzadeh** [haashemi/writer#9]
### Describe Bug
i test more `write` and get this result that i am not sure it is bug or expected functionality (for me it is a bug)
### Expected Behavior
it should not not draw `rld` on the left side of image
### Code Example
```
package main

import (
	"fmt"
	"image"
	"image/color"

	"image/png"
	"os"

	"github.com/haashemi/writer"
	"golang.org/x/image/draw"
)

func main() {
	width := 700
	height := 500
	bgColor := color.RGBA{255, 255, 255, 255}

	img := image.NewRGBA(image.Rect(0, 0, width, height))
	draw.Draw(img, img.Bounds(), &image.Uniform{bgColor}, image.Point{}, draw.Src)

	Textadd(img, "Hello World", 350, 350)

	file, _ := os.Create("output.png")
	defer file.Close()
	png.Encode(file, img)
}

// draw.Draw(img, thumbRect.Add(image.Pt(width/2-thumbRect.Dx()/2, 50)), thumbImg, image.Point{}, draw.Over)

func Textadd(imginput *image.RGBA, myText string, x, y int) {
	face := writer.NewFaceFromFile("/usr/share/fonts/vazirmatn/Vazirmatn-Bold.ttf")
	defer face.Close()

	font := writer.NewFont(face, 85)
	defer font.Close()

	w, err := writer.NewWriter(font, myText, writer.DefaultOptions)
	if err != nil {
		fmt.Println("Error creating writer:", err)
		return
	}
	defer w.Close()

	// Calculate text bounds and position
	textPosition := image.Pt(x, y)

	// Write text to the image
	w.Write(imginput, textPosition, image.Black)
}
```
### More Details Like screanshots etc
current output is like this note to the left side of image that should not show text there
![output](https://github.com/haashemi/writer/assets/25131576/443435ee-6e6b-4966-8ee2-df5ef6279a55)

**Comment by haashemi** [comment]
Thanks for the report.
Yeah, It IS a bug happening [here](https://github.com/haashemi/writer/blob/030253d6c2e48301b8bf46c4780a69230d484686/writer.go#L109).

possible fix is to replace this line with the following code:
```go
// create a temporary image
textImg := image.NewNRGBA(bounds)

// draw the vector on the temporary image
state.vec.Draw(textImg, bounds, color, image.Point{})

// draw the temporary image on the main image
draw.Draw(img, bounds.Add(at), textImg, image.Point{}, draw.Over)
```

But the problem with this code is the performance we lose.
With the code example you provided, it makes it about 5 times slower. (~500µs to ~3ms on my system)

Maybe we could commit it as a temporary fix?

**Comment by haashemi** [comment]
I'm doing the most common way at the moment, which is checking the time difference.

**Comment by haashemi** [comment]
Hi again.
Sorry for the late response.

After further investigation, I've found out that this issue can't really be fixed.

This issue comes from Go's vector package and only occurs with `image.RGBA` (and possibly `image.Alpha`, not tested).

Why this only happends with `image.RGBA`?
Drawing an `image.Uniform` on an `image.RGBA` has its own specific code [here](https://cs.opensource.google/go/x/image/+/master:vector/vector.go;l=287;drc=cff245a6509b8c4de022d0d5b9037c503c5989d6) which calls [this function](https://cs.opensource.google/go/x/image/+/master:vector/vector.go;l=393;drc=3bbf4a659e56fde394e7214ddd17673223aca672) and here's exactly what causes the issue. I didn't really dive into its code to gather more details, but you got the point.

Here are two workarounds I could recommend:
1. Use something else! I'd highly recommend using `image.NRGBA` instead of `image.RGBA` ([reason](https://github.com/haashemi/red-to-white)).

2. Wrap your `image.RGBA` into a different struct so the vector package can't detect it as an `image.RGBA` anymore.

With that said, I'm going to close this issue.
